before:
  hooks:
    - go mod download
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    main: ./cmd
    ldflags:
      - "-s -w -X github.com/devops-works/phpsecscan/main.version={{.Version}} -X github.com/devops-works/phpsecscan/main.buildDate={{.CommitDate}}"
    ignore:
      - goos: darwin
        goarch: 386

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
